- name: Update and Upgrade Linux Servers
  hosts: linuxservers
  tasks:
    - name: Update package list
      sudo apt:
        update_cache: yes

    - name: Upgrade all packages
      sudo apt:
        upgrade: dist
    
    
    